name: "!danger"
markdown: redcarpet
pygments: true
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "tables"]
layout: layout_right
permalink: /post/:title
excerpt_separator: <!--more--> 
paginate: 10
title: "Welcome to Brett's Blog"
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']
